// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiqaswulojpxxjhhgiei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcWFzd3Vsb2pweHhqaGhnaWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODg2NDgsImV4cCI6MjA3MjU2NDY0OH0.1Ljpvrc9Of_9ICbDt0TUWbhE3SbJwnXAsDkMw5cy12E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});